### ISSUE TITLE
Неадекватный тултип на кнопках перелистывания календаря на странице plan

### ISSUE THREAD

**Issue by muturgan** [gregor-tokarev/cubicdone#10]
Тултип закрывает элементы управления, имеет неадекватную подпись.
Так же возможно стоит сделать некоторую задержку на появление этого тултипа - такие элементы управления встречаются часто и большинству пользователей интуитивно и так должно быть понятно что они делают.

https://github.com/user-attachments/assets/3d8a5731-000b-4e15-8d28-4071d0f97884

**Comment by gregor-tokarev** [comment]
Забыл когда, но это уже пофиксил
